apiVersion: v1
kind: BuildConfig
metadata:
  name: java-openjdk
spec:
  triggers:
    - type: ConfigChange
    - type: imageChange
      imageChange:
        from:
          kind: ImageStreamTag
          name: rhel-atomic:latest
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: 'git@github.com:section6nz/openshift-java-openjdk.git'
      ref: master
      contextDir: images/java-openjdk
    sourceSecret:
      name: jenkins-deployment-key
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: rhel-atomic:latest
      noCache: true
  output:
    to:
      kind: ImageStreamTag
      name: 'java-openjdk:latest'
